sudo: required
services:
  - docker

before_install:
  - docker build -t hervs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hervs/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-1"
  env: "Dockerreact1-env"
  bucket_name: "elasticbeanstalk-us-east-1-844476188546"
  bucket-path: "docker-react-1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
